### ISSUE TITLE
Single point of registration for new plugins

### ISSUE THREAD

**Issue by hpiwowar** [figshare/Total-Impact#10]
Ideally we'd only have to change server code in one place to add a new plugin, to make this step as easy and error-proof as possible.  Right now we need to register the handle, and somewhere else add a documentation string to the legend, and somewhere else possibly add support for a new artifact class (section for display).

**Comment by jasonpriem** [comment]
This is an important point, and I've discussed it separately with a few folks. I'm going to make a wiki page for it...let's continue discussion there? https://github.com/mhahnel/Total-Impact/wiki

**Comment by jasonpriem** [comment]
oops, close issue inadvertently.

**Comment by jasonpriem** [comment]
Closing this issue, as it's now addressed by #13, "Encapsulate plugin directories," and #12, "Python plugins: return array of event objects." Together, these will make plugin installation consist of:
1. Drop the plugin directory in the plugins folder, and
2. add the url for the folder to the config file.
