### ISSUE TITLE
Python plugins: return array of event objects

### ISSUE THREAD

**Issue by jasonpriem** [figshare/Total-Impact#12]
Python plugins should:
- accept a JSON-serialized _array_ of IDs (not just one, as is the case now)
- return a JSON-serialized array of _events_, each of which looks like as described on the [plugins wiki page](https://github.com/mhahnel/Total-Impact/wiki/Plugin-requirements)

attn Python plugin authors: @cameronneylon @cdparra @hpiwowar

**Comment by hpiwowar** [comment]
The crossref plugin does this now.  I'll try to get one other plugin to do it in the next day or two, and the rest shortly after.

**Comment by hpiwowar** [comment]
Shall we make the "url" dictionary value be a list rather than a single element?  That way if papers have multiple url synonyms (doi lookup urls, landing pages, even shortened versions) they can all be included for searches.

**Comment by jasonpriem** [comment]
Yes, definitely, but I think that's an after-alpha issue...for now we're 
probably only dealing with CrossRef.

**Comment by hpiwowar** [comment]
that works.  one thought is that we might want to define it as a list right now (that has a maximum of 1 element in current implementation), to avoid moving to a list in the future and breaking existing plugins.  if it is easy.  from the plugin side it is easy :)

**Comment by jasonpriem** [comment]
It is pretty easy, but I've got to leave for Paris in like 20hrs and I'm 
getting a little tight for time...how about we do it toward the end, if 
we have time?

**Comment by hpiwowar** [comment]
ok :)

**Comment by jasonpriem** [comment]
creating URLs-as-lists as a separate issue
