### ISSUE TITLE
Add support for csv download

### ISSUE THREAD

**Issue by hpiwowar** [figshare/Total-Impact#14]
Add support for csv download back in to current report page.  Realistic for this release?

**Comment by jasonpriem** [comment]
I think so. Adding it to milestone.

**Comment by pgroth** [comment]
Yep

Paul

**Comment by hpiwowar** [comment]
Mostly done.  CSV doesn't make too much sense because different sources return different metrics.  Has a "raw text" version popup now.  Can be tweaked if someone has a better idea.
