### ISSUE TITLE
Documentation approach

### ISSUE THREAD

**Issue by cameronneylon** [figshare/Total-Impact#2]
Hi All

I thought I'd make a start on documentation, starting with the plugins. The idea is to create a template python plugin as well as template documentation. By using dexy I can incorporate testing into the documentation so that someone writing a new plugin just needs to drop in the appropriate URL, a couple of test parameters, and their code for parsing and this should both populate the documentation and effectively run the test. I've just created a dexy branch for this purpose which contains such a template but haven't started writing any actual docs as yet.

Any comments on the approach welcome but otherwise I'll try and make some progess over the weekend.

Cheers

Cameron

**Comment by pgroth** [comment]
Sounds good to me.

**Comment by cameronneylon** [comment]
Just looking at the plugins and thinking they probably need to be re-written to have a base plugin class but that's easy enough to do at some later point, I'll work up some template docs to start with and then see how far I get.

Cheers

Cameron

**Comment by pgroth** [comment]
Before rewriting anything I'd like to see the site up and working.

Cool on the docs though

Paul

**Comment by cameronneylon** [comment]
Agreed. I won't touch anything at the moment in terms of running code, and certainly not on the master branch but will try to keep my eye on how the overall design would need to be worked up.

Cheers

Cameron

**Comment by cameronneylon** [comment]
I've just pushed, with a great deal of help from @ananelson a version of the repo to the "dexy" branch on github that includes the beginning of a description of how to write the plugins with documentation that will also act as tests eventually. At the moment the docs just pull to code in but the aim is to incorporate running of the various routines and their results. After that works I'll merge this back into master, then start a new branch with the aim of improving the python plugins with a template class.

**Comment by hpiwowar** [comment]
moving away from this framework; will do api docs a different way.
