### ISSUE TITLE
Update checks pluging data, saves error message if it's malformed

### ISSUE THREAD

**Issue by jasonpriem** [figshare/Total-Impact#20]
Check returned plugin data for correct number/type of fields, including the "about" stuff; if they don't have them, throw them out and save an error "plugin did not format data correctly".

**Comment by hpiwowar** [comment]
low priority

**Comment by hpiwowar** [comment]
added to core roadmap, since may be higher priority when way more plugins:
https://docs.google.com/document/d/1KPjCHKxQ4n31HS6AiqJZRj3f_M1yywKVUjPdjSIKwDg/edit?hl=en_US
