### ISSUE TITLE
Add RDFa to report

### ISSUE THREAD

**Issue by jasonpriem** [figshare/Total-Impact#24]
It would be interesting to look at and perhaps use work from CASRAI here, and I forgot the name of the EU project that's doing similar things but is rather further along...we (Paul, Jason) talked with them at Beyond Impact, you probably recall.

**Comment by cameronneylon** [comment]
For actual Rdf vocabularies you probaby want the work of EuroCRIS, in particular CERIF is the data interchange standard. Not absolutely sure that in it's current form it will do what you want but a good place to start certainly. Hopefully this is the kind of thing that the harmonization exercise will help to produce as well.

Cheers

Cameron

**Comment by hpiwowar** [comment]
closing issue here, adding to the brainstorming doc
