### ISSUE TITLE
Missing keyphrase for the TI server...

### ISSUE THREAD

**Issue by jasonpriem** [figshare/Total-Impact#4]
Sorry, though I wrote this one down, but I can't find it now. Can someone skype it to me?

**Comment by hpiwowar** [comment]
Not close to skype.  Totalimpact I think all lower no hyphen though try variants if nec

**Comment by cdparra** [comment]
If i'm not mistaken, it was 'Total-Impact'

Cristhian Parra
Sent from mobile
-----Mensaje original-----
De: jasonpriem
Enviado:  14/05/2011 21:54:58
Asunto:  [Total-Impact] Missing keyphrase for the TI server... (#4)

Sorry, though I wrote this one down, but I can't find it now. Can someone skype it to me?

## 

Reply to this email directly or view it on GitHub:
https://github.com/mhahnel/Total-Impact/issues/4

**Comment by hpiwowar** [comment]
Ssh key also stored in default file location, logged in as root, can u see it?

**Comment by jasonpriem** [comment]
Found it, no worries :)
