### ISSUE TITLE
Search for DOI gives incorrect result

### ISSUE THREAD

**Issue by tompollard** [figshare/Total-Impact#41]
Searching for 10.5520/SAGECITE-1 (a DataCite DOI) in total-impact.org gives the following record:

10.5520/SAGECITE-1: Baillie J (2011) Survey serves up food for thought. Health Estate.21966695

This is incorrect. doi:10.5520/SAGECITE-1 is a DataCite DOI that resolves to https://sites.google.com/site/sagecitedemorepository/data/sagecite-1 (it's an ugly DOI minted as a test in our early days!)

**Comment by hpiwowar** [comment]
Added DataCite plugin to plugin roadmap for prioritization:  https://docs.google.com/document/d/1vDX6QnNCYCP2bkz5vNN3t81R8_3bMQPNIoSq9P1mX6Q/edit?hl=en_US

Not sure why it returned the wrong record, though, instead of no record?

**Comment by hpiwowar** [comment]
this issue is being tracked as part of the DataCite implementation.  closing ticket here.
