### ISSUE TITLE
Overlapping elements in report

### ISSUE THREAD

**Issue by dartar** [figshare/Total-Impact#44]
line wrapping in the metric columns results in overlapping elements on Safari 5 or Chrome 14/ Mac OS 10.6.8. The problem does not seem to affect FF 5.

Example: third item ("Self-Selected or Mandated, Open Access Increases Citation Impact for Higher Quality Research") of the following collection: http://total-impact.org/report.php?id=PzVDEJ

**Comment by jasonpriem** [comment]
fixed by commit ffab
