### ISSUE TITLE
mendeley pull contacts/groups obscures latest tweets box

### ISSUE THREAD

**Issue by jasonpriem** [figshare/Total-Impact#45]
This is only a problem for long lists of contacts/groups. It's a consequence of the inflexible floated layout. Two possible solutions:
1. make the layout flexible, so the twitter box moves down
2. make it so it lays over the top of the twitter box, with a white background so that you can read it.

**Comment by dartar** [comment]
option 3: display these lists via an overlay so that there is no need to modify the layout.

**Comment by hpiwowar** [comment]
quick workaround for now to make it functional asap (because the bottom groups/contacts weren't clickable): lowered the latest tweets box.  Downside side effect:  Get my metrics button is lower.

Since we are planning to get rid of the large cut and paste box in next UI update, closing this ticket.
