### ISSUE TITLE
Point total-impact.org to Linode nameservers

### ISSUE THREAD

**Issue by jasonpriem** [figshare/Total-Impact#5]
Paul, I don't think I can make the redirect system work with virtual hosts (which I need because 1. it's weird for users to see the 'whohastodoit.com' string in the url, and 2. it's my advisor's server and we need to host multiple domains on it).

So I set up the virtual hosting, and I'll wait for you to set the correct nameservers for the domain. They're: ns[1-5].linode.com (there are five of them, numbered one through five). 

I don't think you need the server's IP address for that, but in case you do it's 72.14.190.127.

**Comment by pgroth** [comment]
Jason,

I think I correctly changed the system. I pointed the A record to the ip 
address you gave me.

Is that correct?

Paul

jasonpriem wrote:

> Paul, I don't think I can make the redirect system work with virtual hosts (which I need because 1. it's weird for users to see the 'whohastodoit.com' string in the url, and 2. it's my advisor's server and we need to host multiple domains on it).
> 
> So I set up the virtual hosting, and I'll wait for you to set the correct nameservers for the domain. They're: ns[1-5].linode.com (there are five of them, numbered one through five).
> 
> I don't think you need the server's IP address for that, but in case you do it's 72.14.190.127.

**Comment by pgroth** [comment]
Ok. It looks like it's now correctly pointing at the server. You get a 
php info page putting in www.total-impact.org.

I think this just needs to be adjusted on you side jason.

cheers,
Paul

jasonpriem wrote:

> Paul, I don't think I can make the redirect system work with virtual hosts (which I need because 1. it's weird for users to see the 'whohastodoit.com' string in the url, and 2. it's my advisor's server and we need to host multiple domains on it).
> 
> So I set up the virtual hosting, and I'll wait for you to set the correct nameservers for the domain. They're: ns[1-5].linode.com (there are five of them, numbered one through five).
> 
> I don't think you need the server's IP address for that, but in case you do it's 72.14.190.127.

**Comment by jasonpriem** [comment]
Great, I'll get on it. If you want to take a look in the server and 
figure out the vHost isn't pointing to the right place, that'd be 
awesome too.
j

**Comment by jasonpriem** [comment]
Ok, works fine for www.total-impact.org, but I think that it has been 
set at only the subdirectory level, because total-impact.org still fails 
to resolve. Can you fix that?
j

**Comment by pgroth** [comment]
Ok, I've pointed total-impact.org to the correct nameserver as well.

pg

jasonpriem wrote:

> Ok, works fine for www.total-impact.org, but I think that it has been
> set at only the subdirectory level, because total-impact.org still fails
> to resolve. Can you fix that?
> j
> 
> On 05/14/2011 08:56 PM, pgroth wrote:
> 
> > Ok. It looks like it's now correctly pointing at the server. You get a
> > php info page putting in www.total-impact.org.
> > 
> > I think this just needs to be adjusted on you side jason.
> > 
> > cheers,
> > Paul
> > 
> > jasonpriem wrote:
> > 
> > > Paul, I don't think I can make the redirect system work with virtual hosts (which I need because 1. it's weird for users to see the 'whohastodoit.com' string in the url, and 2. it's my advisor's server and we need to host multiple domains on it).
> > > 
> > > So I set up the virtual hosting, and I'll wait for you to set the correct nameservers for the domain. They're: ns[1-5].linode.com (there are five of them, numbered one through five).
> > > 
> > > I don't think you need the server's IP address for that, but in case you do it's 72.14.190.127.
