### ISSUE TITLE
New import forms for usability

### ISSUE THREAD

**Issue by dartar** [figshare/Total-Impact#50]
There are way more ID types supported by TI than one would expect just by looking at the import forms on the landing page (and the cool examples page is one click away: too far for most users). This is unfortunate as many people won't realize that TI also tracks regular URLs, software repositories etc.

I suggest we start adding import forms for all the types of artifact currently supported (e.g. software), even if "import" simply means copying the full URL in the main list of IDs. If the page gets too cluttered, we can add some jQuery magic (sliding menus or tabbed interface) to fix it.

**Comment by hpiwowar** [comment]
Idea fleshed out in UI roadmap document:  https://docs.google.com/document/d/1EqVk2OR1NvM1aPU_hmvgVGHe4excNcm8H1GCLnzyQdk/edit?hl=en_US

**Comment by hpiwowar** [comment]
this is being tracked in the product backlog.  closing ticket here.
