### ISSUE TITLE
citation count from Google/Scholar

### ISSUE THREAD

**Issue by dalloliogm** [figshare/Total-Impact#51]
Sorry if this has already been asked. Are you going to include the citation count from Google/Scholar? Compared to scopus and pubmed, Scholar indexes a bigger dataset, and is able to find more citations than the others.

**Comment by hpiwowar** [comment]
Unfortunately Google Scholar data can't be harvested as per their terms of use.  We're trying to only include metrics in Total-Impact that we are allowed to gather.

**Comment by yannickwurm** [comment]
shit that sucks :(

(especially for those of us working in fields poorly covered by pubmed)
