### ISSUE TITLE
change Dryad plugin metric name

### ISSUE THREAD

**Issue by jasonpriem** [figshare/Total-Impact#55]
Can we change the "downloads of most popular file" to "most pop. downloads"? It's way longer than most of the other metric name and consequently breaks the layout right now.

**Comment by hpiwowar** [comment]
Yes.  I will do it in the morning if u don't get to it first.  I suggest "most downloaded file" or "max downloads/file" instead. H

**Comment by jasonpriem** [comment]
yeah, good call; either of those sounds good.

**Comment by hpiwowar** [comment]
changed to "most downloaded file."  Still wraps to three lines, though so does PLoS ALM's "supp data views" and "unique ip views" and maybe others.  what is the longest metric name we want to support?

**Comment by jasonpriem** [comment]
Let's say 20chars for now. Wrapping 3 lines isn't great, but we can live 
with it...4 is a killer.
