### ISSUE TITLE
fix twitter button to use pretty urls

### ISSUE THREAD

**Issue by hpiwowar** [figshare/Total-Impact#57]
right now still uses report.php?

**Comment by jasonpriem** [comment]
fixed

**Comment by dartar** [comment]
Jason fixed it in master, I did it in CleanURL

**Comment by jasonpriem** [comment]
CleanURL has been merged in, so we shoudn't need to worry about keeping 
it up to date, right?

**Comment by dartar** [comment]
I was not sure about the plans: is the CleanURL branch merged and dead or are we going to use it to experiment on dev.total-impact.org?

**Comment by jasonpriem** [comment]
I think it's dead, since the cleanURL problem is mostly solved. We can 
always make new branches for later experiments. Branches in git are 
nicely disposable :)
