### ISSUE TITLE
Facilitate drilldown into metric details

### ISSUE THREAD

**Issue by hpiwowar** [figshare/Total-Impact#9]
Facilitate drill-down into details on the metric values. For example,  when rendering the reuse count for datasets, make the metric statistic clickable so the user can drill into a list of dois of articles that reuse the dataset or follow to a page where that list can be found.  Plugins could return supporting text or links with the metric-values.

**Comment by jasonpriem** [comment]
Is anyone not ok with bumping this down to "after next release?"

**Comment by hpiwowar** [comment]
I'm ok with that plan.

**Comment by hpiwowar** [comment]
done
